config/routes.rb
Rails.application.routes.draw do
  root "bank#index"

  resources :accounts
  resource :session, only: [:new, :create, :destroy]

  get "signup" => "accounts#new"
  get "signin" => "sessions#new"

  get "deposit" => "deposit#new"
  post "deposit" => "deposit#create"

  get "withdrawal" => "withdrawal#new"
  post "withdrawal" => "withdrawal#create"

  get "transference" => "transference#new"
  post "transference" => "transference#create"

  get "balance" => "transactions#check_balance"

  get "statement" => "statement#new"
  get "statement_receipt" => "statement#receipt"

  get "transaction/:id" => "transactions#receipt", as: "transaction_receipt"
end

app/models/account.rb
class Account < ApplicationRecord
  has_many :transactions

  has_secure_password

  attribute :balance, :decimal, default: 0.0

  validates :name, presence: true
  validates :email, presence: true, format: { with: /\S+@\S+/ }, uniqueness: { case_sensitive: false }
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/transaction.rb
class Transaction < ApplicationRecord
  belongs_to :account, optional: true

  validates :type_of_transaction, presence: true
  validates :amount, presence: true

  def self.transference_tax(value, date)
    tax = nil

    if date.monday? || date.tuesday? || date.wednesday? || date.thursday? || date.friday?
      if date.hour >= 9 && date.hour < 18
        tax = 5.0
      else
        tax = 7.0
      end
    else
      tax = 7.0
    end

    if value >= 1000.0
      return tax += 10
    else
      return tax
    end
  end
end

app/controllers/accounts_controller.rb
class AccountsController < ApplicationController
  def index
    @accounts = Account.all
  end

  def show
    @account = Account.find(params[:id])
  end

  def new
    @account = Account.new
  end

  def create
    @account = Account.new(account_params)
    @account.save
    if @account.save
      session[:user_id] = @account.id
      redirect_to root_path, notice: "Conta criada com sucesso, você agora faz parte do Time Nobe!"
    else
      render :new, status: :unprocessable_entity
    end
  end

  def edit
    @account = Account.find(params[:id])
  end

  def update
    @account = Account.find(params[:id])
    if @account.update(account_params)
      redirect_to root_path, notice: "Informações atualizadas com sucesso!"
    else
      render :edit, status: :unprocessable_entity
    end
  end

  def destroy
    @account = Account.find(params[:id])
    @account.active = false
    @account.save
    session[:user_id] = nil
    redirect_to root_path, alert: "Conta desativada!", status: :see_other
  end

private

  def account_params
    params.require(:account).permit(:name, :email, :password, :password_confirmation)
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  def current_user
    Account.find(session[:user_id]) if session[:user_id]
  end

  def transaction_params
    params.require(:transaction).permit!
  end
end

app/controllers/bank_controller.rb
class BankController < ApplicationController
  def index
  end
end

app/controllers/deposit_controller.rb
class DepositController < ApplicationController
  def new
    @transaction = Transaction.new
  end

  def create
    @transaction = Transaction.new(transaction_params)
    @transaction.type_of_transaction = "Depósito"
    @transaction.account = current_user

    if @transaction.save
      destination = Account.find_by(email: @transaction.destination)
      if destination
        destination.balance += @transaction.amount.to_f
        destination.save
        redirect_to transaction_receipt_path(@transaction), notice: "Depósito realizado com sucesso"
      else
        redirect_to deposit_path, status: :unprocessable_entity, alert: "Não encontramos essa conta!"
      end
    else
      redirect_to deposit_path, status: :unprocessable_entity, alert: "Não foi possível realizar sua transação!"
    end
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
  end

  def create
    account = Account.find_by(email: params[:email])
    if account && account.active == true && account.authenticate(params[:password])
      session[:user_id] = account.id
      redirect_to root_path
    elsif account && account.active == false && account.authenticate(params[:password])
      flash.now[:alert] = "Sua conta está desativada! Use outro e-mail ou entre em contato com a nossa equipe."
      render :new, status: :unprocessable_entity
    else
      flash.now[:alert] = "Senha ou email incorretos!"
      render :new, status: :unprocessable_entity
    end
  end

  def destroy
    session[:user_id] = nil
    redirect_to root_path, status: :see_other, notice: "Logout realizado com sucesso!"
  end
end

app/controllers/statement_controller.rb
class StatementController < ApplicationController
  def new
    @transaction = Transaction.new
  end

  def receipt
    user = Account.find(session[:user_id])
    date_from = Date.new params["date_from(1i)"].to_i, params["date_from(2i)"].to_i, params["date_from(3i)"].to_i
    date_to = Date.new params["date_to(1i)"].to_i, params["date_to(2i)"].to_i, params["date_to(3i)"].to_i
    @statement = Transaction.where(:created_at => date_from.beginning_of_day..date_to.end_of_day).where(:account_id => user.id)
  end
end

app/controllers/transactions_controller.rb
class TransactionsController < ApplicationController
  def receipt
    @transaction = Transaction.find(params[:id])
  end

  def check_balance
    @account = current_user
  end
end

app/controllers/transference_controller.rb
class TransferenceController < ApplicationController
  def new
    @transaction = Transaction.new
  end

  def create
    @transaction = Transaction.new(transaction_params)
    @transaction.type_of_transaction = "Transferência"
    @transaction.account = current_user

    if @transaction.save
      destination = Account.find_by(email: @transaction.destination)
      sender = @transaction.account
      @transaction.transference_tax = Transaction.transference_tax(@transaction.amount.to_f, Time.now)

      if destination
        if sender && destination != sender && @transaction.amount.to_f + @transaction.transference_tax <= @transaction.account.balance
          destination.balance += @transaction.amount.to_f
          sender.balance -= @transaction.amount.to_f + Transaction.transference_tax(@transaction.amount.to_f, Time.now)
          destination.save
          sender.save
          @transaction.save
          redirect_to transaction_receipt_path(@transaction), notice: "Depósito realizado com sucesso"
        else
          redirect_to transference_path, status: :unprocessable_entity, alert: "Saldo insuficiente para este saque!"
        end
      else
        redirect_to transference_path, status: :unprocessable_entity, alert: "E-mail do destinatário não encontrado!"
      end
    else
      redirect_to transference_path, status: :unprocessable_entity, alert: "Não foi possível realizar sua transação!"
    end
  end
end

app/controllers/withdrawal_controller.rb
class WithdrawalController < ApplicationController
  def new
    @transaction = Transaction.new
  end

  def create
    @transaction = Transaction.new(transaction_params)
    @transaction.type_of_transaction = "Saque"
    @transaction.account = Account.find(session[:user_id])
    @transaction.destination = ""
    if @transaction.save
      client = Account.find(@transaction.account_id)
      if client && client.balance.to_f >= @transaction.amount.to_f
        client.balance -= @transaction.amount.to_f
        client.save
        redirect_to transaction_receipt_path(@transaction), notice: "Saque realizado com sucesso"
      else
        redirect_to withdrawal_path, status: :unprocessable_entity, alert: "Saldo insuficiente para este saque!"
      end
    else
      redirect_to withdrawal_path, status: :unprocessable_entity, alert: "Não foi possível realizar sua transação!"
    end

  end
end

app/helpers/accounts_helper.rb
module AccountsHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
  def current_user
    Account.find(session[:user_id]) if session[:user_id]
  end
end

app/helpers/bank_helper.rb
module BankHelper
end

app/helpers/deposit_helper.rb
module DepositHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/statement_helper.rb
module StatementHelper
end

app/helpers/transactions_helper.rb
module TransactionsHelper
end

app/helpers/transference_helper.rb
module TransferenceHelper
end

app/helpers/withdrawal_helper.rb
module WithdrawalHelper
end

app/views/accounts/_form.html.erb
<%= form_with(model: account, local: true, class:"row align-items-center w-50 m-auto") do |f| %>

  <%= render "layouts/errors", object: @account %>

  <div class="form-outline mb-4">
    <%= f.label "Nome", class: "form-label" %>
    <%= f.text_field :name, autofocus: true, class: "form-control" %>
  </div>

  <div class="form-outline mb-4">
    <%= f.label "E-mail", class: "form-label" %>
    <%= f.email_field :email, class: "form-control" %>
  </div>

  <div class="form-outline mb-4">
    <%= f.label "Senha", class: "form-label" %>
    <%= f.password_field :password, class: "form-control" %>
  </div>

  <div class="form-outline mb-4">
    <%= f.label :password_confirmation, "Confirme sua senha", class: "form-label" %>
    <%= f.password_field :password_confirmation, class: "form-control" %>
  </div>

  <% if account.new_record? %>
    <%= f.submit "Criar sua conta", class: "btn btn-primary btn-block" %>
  <% else %>
    <%= f.submit "Atualizar sua conta", class: "btn btn-primary btn-block" %>
  <% end %>
<% end %>

app/views/accounts/edit.html.erb
<h1 class="pt-3 pb-3 text-center">Atualize os dados da sua conta</h1>

<%= render "form", account: @account %>

  <h2 class="pt-5 text-center">Deseja desativar sua conta?</h2>
  <p class="text-center">Esta é uma ação irreversível, proceda com cautela.</p>

<div class="d-flex justify-content-center">
  <%= link_to "Desativar sua conta", @account, data: { turbo_method: :delete, turbo_confirm: "Você tem certeza?" }, class: "btn btn-danger text-center"%>
</div>

app/views/accounts/index.html.erb
<h1 class="p-3">Todos os usuários cadastrados</h1>
<ul>
  <% @accounts.each do |a| %>
  <li><%= a.name %></li>
  <% end %>
</ul>

app/views/accounts/new.html.erb
<h1 class="p-3">Abra sua conta</h1>

<%= render "form", account: @account %>

app/views/bank/index.html.erb
<h1 class="p-3">Bem vindo ao Caixa Eletrônico<%= ", #{current_user.name}" if current_user %></h1>

<div class="container">
  <div class="row gap-3">

    <div class="col">
      <div class="card" style="width: 18rem;">
        <%= image_tag "deposito.jpg", class:"card-img-top" %>
        <div class="card-body">
          <h5 class="card-title">Depósito</h5>
          <p class="card-text">Deposite aqui o seu dinheiro físico.</p>
          <%= link_to "Faça um depósito", deposit_path, class: "btn btn-primary" %>
        </div>
      </div>
    </div>

    <% if current_user %>
    <div class="col">
      <div class="card" style="width: 18rem;">
        <%= image_tag "saque.jpg", class:"card-img-top" %>
        <div class="card-body">
          <h5 class="card-title">Saque</h5>
          <p class="card-text">Faça uma retirada de dinheiro direto da sua conta.</p>
          <%= link_to "Faça um saque", withdrawal_path, class: "btn btn-primary" %>
        </div>
      </div>
    </div>

    <div class="col">
      <div class="card" style="width: 18rem;">
        <%= image_tag "transferencia.jpg", class:"card-img-top" %>
        <div class="card-body">
          <h5 class="card-title">Transferência</h5>
          <p class="card-text">Transfira dinheiro para outra Conta Nobe.</p>
          <%= link_to "Faça uma transferência", transference_path, class: "btn btn-primary" %>
        </div>
      </div>
    </div>

    <div class="col">
      <div class="card" style="width: 18rem;">
        <%= image_tag "saldo.jpg", class:"card-img-top" %>
        <div class="card-body">
          <h5 class="card-title">Saldo</h5>
          <p class="card-text">Confira aqui quanto dinheiro você tem na sua conta.</p>
          <%= link_to "Confira seu saldo", balance_path, class: "btn btn-primary" %>
        </div>
      </div>
    </div>

    <div class="col">
      <div class="card" style="width: 18rem;">
        <%= image_tag "extrato.jpg", class:"card-img-top" %>
        <div class="card-body">
          <h5 class="card-title">Extrato</h5>
          <p class="card-text">Veja com detalhes as transações da sua conta.</p>
          <%= link_to "Veja seu extrato", statement_path, class: "btn btn-primary" %>
        </div>
      </div>
    </div>

    <% end %>
  </div>
</div>

app/views/deposit/new.html.erb
<h1 class="text-center pt-3 pb-3">Faça um depósito</h1>

<%= form_with(model: @transaction, url: deposit_path, local: true, class:"row align-items-center w-50 m-auto") do |f| %>
  <div class="form-outline mb-4">
    <%= f.label "E-mail do destinatário", class: "form-label" %>
    <%= f.text_field :destination, autofocus: true, class: "form-control" %>
  </div>

  <div class="form-outline mb-4">
    <%= f.label "Quantidade", class: "form-label" %>
    <%= f.number_field :amount, step: :any, class: "form-control" %>
  </div>

  <%= f.submit "Fazer o depósito", class: "btn btn-primary btn-block" %>
<% end %>

app/views/statement/new.html.erb
<h1 class="pt-3 pb-3 text-center">Insira a data dos dados desejados</h1>

<%= form_with(url: statement_receipt_path, local: true, :method => :get, class:"row align-items-center w-50 m-auto") do |f| %>
  <div class="form-outline mb-4">
    <%= f.label "Data de início", class: "form-label" %>
    <%= f.date_select :date_from, class: "form-control" %>
  </div>

  <div class="form-outline mb-4">
    <%= f.label "Data final", class: "form-label" %>
    <%= f.date_select :date_to, class: "form-control" %>
  </div>

  <%= f.submit "Criar seu extrato", class: "btn btn-primary btn-block" %>
<% end %>

app/views/statement/receipt.html.erb
<table class="table">
  <thead>
    <tr>
      <th scope="col">#</th>
      <th scope="col">Tipo da Transação</th>
      <th scope="col">Data da Transação</th>
      <th scope="col">Quantidade</th>
      <th scope="col">Destinatário</th>
      <th scope="col">Taxa</th>
    </tr>
  </thead>
  <tbody>
    <% @statement.each do |s| %>
    <tr>
      <th scope="row"><%= s.id %>
      <td><%= s.type_of_transaction %></td>
      <td><%= s.created_at.strftime("%d/%m/%Y") %></td>
      <td><%= number_to_currency(s.amount, unit: "R$", separator: ",", delimiter: "") %></td>
      <td><%= s.destination if !s.destination.empty? %></td>
      <td><%= s.transference_tax if !s.destination.empty? %></td>
    </tr>
    <% end %>
  </tbody>
</table>

app/views/transactions/check_balance.html.erb
<%= image_tag "cofrinho.png", size:"200x200", class:"rounded mx-auto d-block " %>
<h1 class="text-center">Seu saldo é de <%= number_to_currency(@account.balance, unit: "R$", separator: ",", delimiter: "") %></h1>

app/views/transactions/deposit_new.html.erb
<h1 class="text-center pt-3 pb-3">Faça um depósito</h1>

<%= form_with(model: @transaction, url: deposit_path, local: true, class:"row align-items-center w-50 m-auto") do |f| %>
  <div class="form-outline mb-4">
    <%= f.label "E-mail do destinatário", class: "form-label" %>
    <%= f.text_field :destination, autofocus: true, class: "form-control" %>
  </div>

  <div class="form-outline mb-4">
    <%= f.label "Quantidade", class: "form-label" %>
    <%= f.number_field :amount, step: :any, class: "form-control" %>
  </div>

  <%= f.submit "Fazer o depósito", class: "btn btn-primary btn-block" %>
<% end %>

app/views/transactions/receipt.html.erb
<div class="p-5">
<div class="card">
  <div class="card-body mx-4">
    <div class="container">
      <p class="my-5 mx-5" style="font-size: 30px;">Transação realizada com sucesso!</p>
      <div class="row">
        <ul class="list-unstyled">
          <li class="text-black"><%= @transaction.account.name if @transaction.account %></li>
          <li class="text-muted mt-1"><span class="text-black">Transação</span> #<%= @transaction.id %></li>
          <li class="text-black mt-1"><%= @transaction.created_at %></li>
        </ul>
        <hr>
        <div class="col-xl-10">
          <p><%= @transaction.type_of_transaction %><%= " para #{@transaction.destination}" if !@transaction.destination.empty? %></p>
        </div>
        <div class="col-xl-2">
          <p class="float-end"><%= number_to_currency(@transaction.amount, unit: "R$", separator: ",", delimiter: "") %>
          </p>
        </div>
        <hr>
      </div>
      <% if @transaction.type_of_transaction == "Transferência" %>
      <div class="row">
        <div class="col-xl-10">
          <p>Taxa de transferência</p>
        </div>
        <div class="col-xl-2">
          <p class="float-end"><%= number_to_currency(@transaction.transference_tax, unit: "R$", separator: ",", delimiter: "") %>
          </p>
        </div>
        <hr>
      </div>
      <% end %>
    </div>
  </div>
</div>
</div>

app/views/transactions/statement_new.html.erb
<h1 class="pt-3 pb-3 text-center">Insira a data dos dados desejados</h1>

<%= form_with(url: statement_receipt_path, local: true, :method => :get, class:"row align-items-center w-50 m-auto") do |f| %>
  <div class="form-outline mb-4">
    <%= f.label "Data de início", class: "form-label" %>
    <%= f.date_select :date_from, class: "form-control" %>
  </div>

  <div class="form-outline mb-4">
    <%= f.label "Data final", class: "form-label" %>
    <%= f.date_select :date_to, class: "form-control" %>
  </div>

  <%= f.submit "Criar seu extrato", class: "btn btn-primary btn-block" %>
<% end %>

app/views/transactions/statement_receipt.html.erb
<table class="table">
  <thead>
    <tr>
      <th scope="col">#</th>
      <th scope="col">Tipo da Transação</th>
      <th scope="col">Data da Transação</th>
      <th scope="col">Quantidade</th>
      <th scope="col">Destinatário</th>
      <th scope="col">Taxa</th>
    </tr>
  </thead>
  <tbody>
    <% @statement.each do |s| %>
    <tr>
      <th scope="row"><%= s.id %>
      <td><%= s.type_of_transaction %></td>
      <td><%= s.created_at.strftime("%d/%m/%Y") %></td>
      <td><%= number_to_currency(s.amount, unit: "R$", separator: ",", delimiter: "") %></td>
      <td><%= s.destination if !s.destination.empty? %></td>
      <td><%= s.transference_tax if !s.destination.empty? %></td>
    </tr>
    <% end %>
  </tbody>
</table>

app/views/transactions/transference_new.html.erb
<h1 class="text-center pt-3 pb-3">Faça uma transferência</h1>

<%= form_with(model: @transaction, url: transference_path, local: true, class:"row align-items-center w-50 m-auto") do |f| %>
  <div class="form-outline mb-4">
    <%= f.label "E-mail do destinatário", class: "form-label" %>
    <%= f.text_field :destination, autofocus: true, class: "form-control" %>
  </div>

  <div class="form-outline mb-4">
    <%= f.label "Quantidade", class: "form-label" %>
    <%= f.number_field :amount, step: :any, class: "form-control" %>
  </div>

  <%= f.submit "Fazer a transferência", class: "btn btn-primary btn-block" %>
<% end %>

app/views/transactions/withdrawal_new.html.erb
<h1 class="text-center pt-3 pb-3">Realize um saque da sua conta</h1>

<%= form_with(model: @transaction, url: withdrawal_path, local: true, class:"row align-items-center w-50 m-auto") do |f| %>
  <div class="form-outline mb-4">
    <%= f.label "Quantidade", class: "form-label" %>
    <%= f.number_field :amount, step: :any, class: "form-control" %>
  </div>

  <%= f.submit "Fazer o saque", class: "btn btn-primary btn-block" %>
<% end %>

app/views/transference/new.html.erb
<h1 class="text-center pt-3 pb-3">Faça uma transferência</h1>

<%= form_with(model: @transaction, url: transference_path, local: true, class:"row align-items-center w-50 m-auto") do |f| %>
  <div class="form-outline mb-4">
    <%= f.label "E-mail do destinatário", class: "form-label" %>
    <%= f.text_field :destination, autofocus: true, class: "form-control" %>
  </div>

  <div class="form-outline mb-4">
    <%= f.label "Quantidade", class: "form-label" %>
    <%= f.number_field :amount, step: :any, class: "form-control" %>
  </div>

  <%= f.submit "Fazer a transferência", class: "btn btn-primary btn-block" %>
<% end %>

app/views/withdrawal/new.html.erb
<h1 class="text-center pt-3 pb-3">Realize um saque da sua conta</h1>

<%= form_with(model: @transaction, url: withdrawal_path, local: true, class:"row align-items-center w-50 m-auto") do |f| %>
  <div class="form-outline mb-4">
    <%= f.label "Quantidade", class: "form-label" %>
    <%= f.number_field :amount, step: :any, class: "form-control" %>
  </div>

  <%= f.submit "Fazer o saque", class: "btn btn-primary btn-block" %>
<% end %>