config/routes.rb
Rails.application.routes.draw do
  root "bank#index"

  resources :accounts
  resource :session, only: [:new, :create, :destroy]

  get "signup" => "accounts#new"
  get "signin" => "sessions#new"

  get "deposit" => "deposit#new"
  post "deposit" => "deposit#create"

  get "withdrawal" => "withdrawal#new"
  post "withdrawal" => "withdrawal#create"

  get "transference" => "transference#new"
  post "transference" => "transference#create"

  get "balance" => "transactions#check_balance"

  get "statement" => "statement#new"
  get "statement_receipt" => "statement#receipt"

  get "transaction/:id" => "transactions#receipt", as: "transaction_receipt"
end

app/models/account.rb
class Account < ApplicationRecord
  has_many :transactions

  has_secure_password

  attribute :balance, :decimal, default: 0.0

  validates :name, presence: true
  validates :email, presence: true, format: { with: /\S+@\S+/ }, uniqueness: { case_sensitive: false }
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/transaction.rb
class Transaction < ApplicationRecord
  belongs_to :account, optional: true

  validates :type_of_transaction, presence: true
  validates :amount, presence: true

  def self.transference_tax(value, date)
    tax = nil

    if date.monday? || date.tuesday? || date.wednesday? || date.thursday? || date.friday?
      if date.hour >= 9 && date.hour < 18
        tax = 5.0
      else
        tax = 7.0
      end
    else
      tax = 7.0
    end

    if value >= 1000.0
      return tax += 10
    else
      return tax
    end
  end
end

app/controllers/accounts_controller.rb
class AccountsController < ApplicationController
  def index
    @accounts = Account.all
  end

  def show
    @account = Account.find(params[:id])
  end

  def new
    @account = Account.new
  end

  def create
    @account = Account.new(account_params)
    @account.save
    if @account.save
      session[:user_id] = @account.id
      redirect_to root_path, notice: "Conta criada com sucesso, você agora faz parte do Time Nobe!"
    else
      render :new, status: :unprocessable_entity
    end
  end

  def edit
    @account = Account.find(params[:id])
  end

  def update
    @account = Account.find(params[:id])
    if @account.update(account_params)
      redirect_to root_path, notice: "Informações atualizadas com sucesso!"
    else
      render :edit, status: :unprocessable_entity
    end
  end

  def destroy
    @account = Account.find(params[:id])
    @account.active = false
    @account.save
    session[:user_id] = nil
    redirect_to root_path, alert: "Conta desativada!", status: :see_other
  end

private

  def account_params
    params.require(:account).permit(:name, :email, :password, :password_confirmation)
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  def current_user
    Account.find(session[:user_id]) if session[:user_id]
  end

  def transaction_params
    params.require(:transaction).permit!
  end
end

app/controllers/bank_controller.rb
class BankController < ApplicationController
  def index
  end
end

app/controllers/deposit_controller.rb
class DepositController < ApplicationController
  def new
    @transaction = Transaction.new
  end

  def create
    @transaction = Transaction.new(transaction_params)
    @transaction.type_of_transaction = "Depósito"
    @transaction.account = current_user

    if @transaction.save
      destination = Account.find_by(email: @transaction.destination)
      if destination
        destination.balance += @transaction.amount.to_f
        destination.save
        redirect_to transaction_receipt_path(@transaction), notice: "Depósito realizado com sucesso"
      else
        redirect_to deposit_path, status: :unprocessable_entity, alert: "Não encontramos essa conta!"
      end
    else
      redirect_to deposit_path, status: :unprocessable_entity, alert: "Não foi possível realizar sua transação!"
    end
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
  end

  def create
    account = Account.find_by(email: params[:email])
    if account && account.active == true && account.authenticate(params[:password])
      session[:user_id] = account.id
      redirect_to root_path
    elsif account && account.active == false && account.authenticate(params[:password])
      flash.now[:alert] = "Sua conta está desativada! Use outro e-mail ou entre em contato com a nossa equipe."
      render :new, status: :unprocessable_entity
    else
      flash.now[:alert] = "Senha ou email incorretos!"
      render :new, status: :unprocessable_entity
    end
  end

  def destroy
    session[:user_id] = nil
    redirect_to root_path, status: :see_other, notice: "Logout realizado com sucesso!"
  end
end

app/controllers/statement_controller.rb
class StatementController < ApplicationController
  def new
    @transaction = Transaction.new
  end

  def receipt
    user = Account.find(session[:user_id])
    date_from = Date.new params["date_from(1i)"].to_i, params["date_from(2i)"].to_i, params["date_from(3i)"].to_i
    date_to = Date.new params["date_to(1i)"].to_i, params["date_to(2i)"].to_i, params["date_to(3i)"].to_i
    @statement = Transaction.where(:created_at => date_from.beginning_of_day..date_to.end_of_day).where(:account_id => user.id)
  end
end

app/controllers/transactions_controller.rb
class TransactionsController < ApplicationController
  def receipt
    @transaction = Transaction.find(params[:id])
  end

  def check_balance
    @account = current_user
  end
end

app/controllers/withdrawal_controller.rb
class WithdrawalController < ApplicationController
  def new
    @transaction = Transaction.new
  end

  def create
    @transaction = Transaction.new(transaction_params)
    @transaction.type_of_transaction = "Saque"
    @transaction.account = Account.find(session[:user_id])
    @transaction.destination = ""
    if @transaction.save
      client = Account.find(@transaction.account_id)
      if client && client.balance.to_f >= @transaction.amount.to_f
        client.balance -= @transaction.amount.to_f
        client.save
        redirect_to transaction_receipt_path(@transaction), notice: "Saque realizado com sucesso"
      else
        redirect_to withdrawal_path, status: :unprocessable_entity, alert: "Saldo insuficiente para este saque!"
      end
    else
      redirect_to withdrawal_path, status: :unprocessable_entity, alert: "Não foi possível realizar sua transação!"
    end

  end
end

app/helpers/accounts_helper.rb
module AccountsHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
  def current_user
    Account.find(session[:user_id]) if session[:user_id]
  end
end

app/helpers/bank_helper.rb
module BankHelper
end

app/helpers/deposit_helper.rb
module DepositHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/statement_helper.rb
module StatementHelper
end

app/helpers/transactions_helper.rb
module TransactionsHelper
end

app/helpers/transference_helper.rb
module TransferenceHelper
end

app/helpers/withdrawal_helper.rb
module WithdrawalHelper
end

app/views/layouts/_errors.html.erb
<% if object.errors.any? %>
  <section class="alert alert-danger">
    <h2>
      Houve um erro!
    </h2>
    <h3>
      Por favor, corrija os seguintes pontos:
      <%= pluralize(object.errors.size, "erro") %>:
    </h3>
    <ul>
      <% object.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  </section>
<% end %>

app/views/layouts/_flash.html.erb
<div class="pt-4 pb-2">
  <% if flash[:notice] %>
    <div class="alert alert-primary">
      <%= flash[:notice] %>
    </div>
  <% end %>

  <% if flash[:alert] %>
    <div class="alert alert-danger">
      <%= flash[:alert] %>
    </div>
  <% end %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>BancoNobe</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <header class="p-3 text-white" style="background-color: #142460;">
      <div class="container">
        <div class="d-flex flex-wrap align-items-center justify-content-between ">
          <div>
          <a href="/" class="d-flex align-items-center mb-2 mb-lg-0 text-white text-decoration-none">
            Caixa Eletrônico
          </a>
          </div>

          <div>
            <% if current_user %>
              <%= link_to "Edite sua conta", edit_account_path(current_user), class: "btn btn-outline-light me-" %>
              <%= link_to "Sair", session_path, data: { turbo_method: :delete }, class: "btn btn-outline-light"%>
            <% else %>
              <%= link_to "Acesse sua conta", signin_path, class: "btn btn-outline-light me-2" %>
              <%= link_to "Abra sua conta", signup_path, class: "btn btn-warning" %>
            <% end %>
          </div>
        </div>
      </div>
    </header>

    <div class="container pb-5">
      <%= render "layouts/flash" %>
      <%= yield %>
    </div>

    <footer class="text-center p-4" style="background-color: rgba(0, 0, 0, 0.05);">
      <p>Projeto desenvolvido para teste corporativo por <%= link_to "Devanil", 'http://devanil.dev' %>. Todas as informações e imagens utilizadas não tem fins comerciais.</p>
    </footer>
  </body>
</html>